cmd -> Wundow(Centra_Argo_Integro){


	_HAX_SLASH#101010101();
	__RECOOR::PING();

	TANS_MAN_KUNGU();

RADIOHEAD(); MIC_CHECK(); 

AL_FIN(PHO###);

GSM::GEET(PHO###[]); DIALILATE(PHO###[]);

SEND_KEYSTROKE::DEATHPOOL::AUTO::MICVOE::SIGNAL(){
 ###***##**##***1100192010112091020102##**};


SEND_SPEECH::DEATHPOOL::AUTO::AIFACTORY(){

`HELLO WORLD IT IS A BEAUTIFUL DAY FOR A NEW BEGANNING WOULDNT MIND IF THE SUN IS OUT AT FIVE OH CLOCK SOMEWHERE DANCE IN THE RAIN TONIGHT LET THE SKY SHINE MOON REAPER COME AND FIND ME

ECHO 1 2 4 1 3 2 1 6 9 0 9 1 9 0 0 2 0 1 3 5

}


SEND_ALARM(){

DFN_E::CLASMATE::OK::NEGA::COLD_WHITE;

}

}








}